# Generated by Django 4.1 on 2022-08-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('arabic', models.DecimalField(decimal_places=1, max_digits=4)),
                ('math', models.DecimalField(decimal_places=1, max_digits=4)),
                ('english', models.DecimalField(decimal_places=1, max_digits=4)),
                ('social', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('islamic', models.DecimalField(decimal_places=1, max_digits=4)),
                ('olenglish', models.DecimalField(decimal_places=1, max_digits=4)),
                ('computer', models.DecimalField(decimal_places=1, max_digits=4)),
                ('art', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
